### ISSUE TITLE
Some probelm in PCC_set in CPU

### ISSUE THREAD

**Issue by xichaoqiang** [sergiventosa/FastPCC#1]
Dear Dr. Ventosa,

Thank you for sharing this exceptional package.

I am attempting to analyze two signals using different CC methods. However, I've encountered an issue with the results from the PCC method; it appears that they should be flipped.

Could you please assist me in verifying this?

Best regards,

![image](https://github.com/sergiventosa/FastPCC/assets/30900789/19bac09d-be81-4c41-8f6b-79133f550f6f)

Best regards,
Xi

**Comment by xichaoqiang** [comment]
Here is my test code 
![image](https://github.com/sergiventosa/FastPCC/assets/30900789/a7d73268-c184-4701-ae2f-a1d47496686f)

**Comment by sergiventosa** [comment]
Hi Xi,

In the CPU version, the virtual source and receiver were swapped for PCC in the pcc_set function that is called only when v different than 1 and 2. The have already updated the code.

Thanks a lot for pointing out to this issue!

Regards,
Sergi
