### ISSUE TITLE
The result of PCC2 not equal PCC with power= 2

### ISSUE THREAD

**Issue by xichaoqiang** [sergiventosa/FastPCC#2]
In the first scenario, where I set v=1, the results from PCC1 and PCC with a power of 1 appear to be identical. Conversely, in the second scenario, despite setting v=2, the outcomes from PCC2 and PCC with a power of 2 do not seem to match.
![image](https://github.com/sergiventosa/FastPCC/assets/30900789/b3af4304-2741-4491-ae77-811131a1cd67)

![image](https://github.com/sergiventosa/FastPCC/assets/30900789/93c13a4e-7f8b-4eaf-9a06-a676d576e319)

**Comment by sergiventosa** [comment]
Dear Xi,

I am not fully sure what it happens from the figures alone. I guess it could be just a misunderstood on the parameters. Which parameters have you used?

The only parameters defining correlations are ccgn, cc1b, pcc and wpcc. You can put several together, but pcc1 and pcc2 are currently not defined. I would say the issue arise because the code reads pcc1 and pcc2 as pcc (ignoring the number).

By default pcc computes PCC2 because the default value of v is 2. To compute PCC1 you must set v=1.

Best,
Sergi

**Comment by xichaoqiang** [comment]
I wrap the FFTapps.c to matlab mex.

Here is my code.

When I set different v values to  pcc_set ,and compare the result with pcc2_set and pcc1_set.

![image](https://github.com/sergiventosa/FastPCC/assets/30900789/23ef3ed3-b21a-4c3c-a5d2-630b3e488521)

**Comment by xichaoqiang** [comment]
I have successfully encapsulated the FFTapps.c functionality into a MATLAB MEX file. Below is my implementation:

Upon varying the 'v' parameter in pcc_set and subsequently comparing the outcomes with those obtained from pcc2_set and pcc1_set, I am able to conduct a comprehensive analysis of the results.

I swap the x2 and x1 in pcc_set here.

![image](https://github.com/sergiventosa/FastPCC/assets/30900789/8c355526-e90d-4f57-85e5-d78820602dde)

**Comment by sergiventosa** [comment]
Dear Xi,

The pcc2_set and tspccw2_set functions currently use a slightly different normalization than the others. The correlation in these two functions is normalized by the length of the sequences, N, while in the others is normalized by actual samples involved in the correlation at each lag time, N-|lag|. Each option have pros and cons, see bias and unbiased correlation estimators. But, the maximum lag time in seismic ambient-noise applications is typically much lower than the length of the sequence anyway.

Aside, seeing the correlations at lags where the sines does not overlap, it looks like the correlation of the small regularization noise added in the input sequence is not close to zero.

Sergi

**Comment by xichaoqiang** [comment]
Thanks for your reply.It helps me alot.
